### ISSUE TITLE
Check only python files

### ISSUE THREAD

**Issue by mdsrosa** [AtomLinter/linter-flake8#114]
I've been using this package for while now and works great. But is very annoying that it keeps checking non-python files.

Is it possible to only validate `*.py` files?

Thanks!

**Comment by Arcanemagus** [comment]
This package only lints files with one of these scopes:
* `source.python`
* `source.python.django`

If you are seeing it lint anything that doesn't seem to make sense check the scopes at the position of your cursor by using the `Editor: Log Cursor Scope` command. If I had to guess you are seeing this on Markdown files as the default package for those for Atom has major issues with putting the wrong scope in place. (`source.python` instead of `source.embedded.python`)

I'm marking this as closed, but if you see any file that this is somehow running on that _doesn't_ have one of those scopes at your current cursor position I would love to see it.

**Comment by mdsrosa** [comment]
@Arcanemagus Thank you for the response. You're right. I'm seeing this in Markdown files. Is there already a issue reported about this in Atom's project?

**Comment by Arcanemagus** [comment]
I don't think there is one for Python yet, but here is the one for Javascript: https://github.com/atom/language-gfm/issues

As mentioned there you can try disabling the `language-gfm` package and installing [language-markdown](https://atom.io/packages/language-markdown), but be warned that the Markdown Preview package seems to depend on `language-gfm` as it stops working for me when I make that switch.
