### ISSUE TITLE
Linter-flake8 doesn't resolve the configuration as flake8

### ISSUE THREAD

**Issue by johnchristopherjones** [AtomLinter/linter-flake8#124]
This is related to #8.

Generally, it appears that `linter-flake8` isn't actually resolving config files the same way `flake8` natively does.  My immediate problem is that `linter-flake8` is only picking up config settings if the config file is in the _same_ directory as the project file.  If the project file is in a subdirectory, the config settings are ignored.  By contrast, `flake8` itself relies on a config file if it appears in the project directory (or anywhere in the direct directory ancestry).  

`linter-flake8` should also pick up user configs like `~/.config/flake8`, but it doesn't appear to do so, at least from a virtual environment.

Here's an example project folder that reproduces the problem:

```
app/
    __init__.py       # Raises D203 warning
    package/
        __init__.py   # Raises D203 warning
.pep257               # Says to ignore D203 warnings
myscript.py           # Ignores D203 warnings
```

**Comment by Arcanemagus** [comment]
It should match `flake8` on the command line exactly if you don't specify a custom name in the settings, if you do though it looks like [currently](https://github.com/AtomLinter/linter-flake8/blob/v1.9.2/lib/main.coffee#L163) it will assume the configuration file is in the root of the project.

You could use `helpers.find()` to search for it though pretty simply if you want to submit a PR, I'm not going to have time to do that for a while myself.

**Comment by ssbarnea** [comment]
I totally agree that the default behaviour should match the one of the flake8 command line tool. Why are we supposed to populate the **Config File Names** section when there is a clear rule regarding how flake8 loads them?

The default config should be something like `tox.init, setup.cfg, .flake8rc` instead of empty. Yep, is ok to be able to customise settings but clearly less important than matching already standard default behaviours of the flake8. 

I would be glad to get rid of the config file names completely if the behaviour would match the one of flake8.

**Comment by popas90** [comment]
I'm having a problem which seems very similar. I have a `.flake8rc` file containing the following lines:
```
[flake8]
exclude=generated/*
```

The `.flake8rc` is placed at the same level as the `generated` directory, at the root of the project. However, the settings are ignored. The file is set as the Project Config file.

I posted about this issue here:
http://stackoverflow.com/questions/39315998/can-linter-flake8-ignore-files-by-using-a-project-wide-flake8rc
