### ISSUE TITLE
Mutually exclusive Flake8 warnings

### ISSUE THREAD

**Issue by IrSent** [AtomLinter/linter-flake8#127]
### Don't know if it is a bug

> D203 - 1 blank line required before class docstring
<img width="557" alt="screen shot 2015-12-16 at 00 39 57" src="https://cloud.githubusercontent.com/assets/3392655/11826514/7d7354a6-a38e-11e5-8f65-c6e28ea03019.png">
and
> D211 - No blank lines allowed before class docstring
<img width="591" alt="screen shot 2015-12-16 at 00 40 10" src="https://cloud.githubusercontent.com/assets/3392655/11826515/7d74db96-a38e-11e5-8fe9-4bb7552093c4.png">

**Comment by Arcanemagus** [comment]
This is related to https://gitlab.com/pycqa/flake8-docstrings/issues/8, personally I have just put D203 into the list of ignored error codes in the settings as D211 is meant to supersede it.

Marking this as closed since this is an issue of configuration of the linter and not `linter-flake8` misbehaving :wink:.

**Comment by IrSent** [comment]
Oh, sorry! Should've dig deeper into that. Thanks!

**Comment by Arcanemagus** [comment]
No problem, glad I could help.
