### ISSUE TITLE
Linter checks markdown?

### ISSUE THREAD

**Issue by pyvim** [AtomLinter/linter-flake8#130]
Hello there!

Why linter active in markdown files?

![2015-12-17 12 59 22](https://cloud.githubusercontent.com/assets/4338636/11866733/06f75fd0-a4be-11e5-89ec-795cc182c18a.png)

**Comment by Arcanemagus** [comment]
Because the built in Markdown package (language-gfm) for some bizarre reason marks all embedded code as the _full_ scope, meaning linters think you are editing a file of that type while your cursor is in that block.

I would highly recommend checking out [language-markdown](https://atom.io/packages/language-markdown) as it properly marks embedded code as such.
