### ISSUE TITLE
Is there a way to have errors popup on right side of screen?

### ISSUE THREAD

**Issue by corysimmons** [AtomLinter/linter-flake8#136]
When I get to bottom of a file and start writing code it pops up errors over top of my code. I end up having to put a dozen newlines at the bottom of my file and turning off my EOF newline trimmer while coding.

Is there a way with Atom to have the errors pop up on a right side toolbar or something?

**Comment by Arcanemagus** [comment]
I'm marking this as closed due to the fact that this is entirely handled by [linter](https://github.com/atom-community/linter/).

That being said, there is a re-write of the UI being worked on [here](https://github.com/AtomLinter/linter-ui-default), allowing much easier fixes to things, you might want to file an issue over there to see what can be done about this.

**Comment by corysimmons** [comment]
Cool, thanks!
