### ISSUE TITLE
Linter triggered on Markdown file

### ISSUE THREAD

**Issue by zacbri** [AtomLinter/linter-flake8#146]
For some reason, the linter is being triggered on my README.md.  
Any idea where this might be coming from ?

Atom version : 1.3.3
Linter-flake8 : 1.10.0

**Comment by Arcanemagus** [comment]
The currently released version of `language-gfm` (the built in Markdown language support in Atom) has a bug where _all_ embedded source code is marked as the full source instead of embedded. Thankfully this is fixed in the current version of it, but the released version is dependent on the Atom version so I'm not sure when this will come out to users.

For now you can install `language-markdown` which fixes this issue.

**Comment by zacbri** [comment]
Thanks for the tip. Works great
