### ISSUE TITLE
Incompatibility with auto-detect-indentation

### ISSUE THREAD

**Issue by keul** [AtomLinter/linter-flake8#207]
When I activate both this plugin and [auto-detect-indentation](https://atom.io/packages/auto-detect-indentation) I get a strange issue about closing brackets: "*E133 for closing bracket which is missing indentation*".

This happen at every closing bracket with indentation. So a code like the folliwing will report the issue:

    a = {
        'fff': 5
    }

If I change the indentation as the following the error disappear (but obviously the indentation is wrong):

    a = {
        'fff': 5
        }

...not sure if the issue is here on in the other plugin.

**Comment by Arcanemagus** [comment]
This package is just forwarding on the messages from `flake8`, you would need to file an issue on that if you think this is something that should be fixed there.

That being said `pycodestyle` (which `flake8` integrates) claims that in their default configuration E133 is ignored. Because of the way `flake8` integrates it, this default ignore is... ignored. I would recommend just adding `E133` to your list of Ignored Error Codes in this package.

**Comment by keul** [comment]
Thanks for details.
The fact is that if I manually call pyflakes on the file I have the right output (the same pyflakes configured to be used by the linter).

But I still think there's (again) something wrong with my environment (I'm the same guy of issue #140 and I never fixed that one either 😄)
