### ISSUE TITLE
Flake8 rule 'E231' reported an invalid point

### ISSUE THREAD

**Issue by mgdreamingstar** [AtomLinter/linter-flake8#378]
Flake8 reported an invalid point for the rule `E231`, with the messge `missing whitespace after ','`.

Debug information:
Atom version: 1.15.0
Flake8 version: `3.3.0 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.5.0) CPython 2.7.10 on Windows`

**Comment by Arcanemagus** [comment]
Do you have unicode characters in the source code? There is a known bug with regards to that that could be causing this.

**Comment by mgdreamingstar** [comment]
yes, there are some unicode characters.

**Comment by Arcanemagus** [comment]
Ah, it's very likely that [pycqa/flake8#306](https://gitlab.com/pycqa/flake8/issues/306) is the problem here then. It's been fixed on the `master` branch of `flake8`, but not yet released. Marking this as closed since there is nothing we can do about it here, and it will be fixed in the next release on their end.
