### ISSUE TITLE
virtualenvwrapper issues

### ISSUE THREAD

**Issue by cjm715** [AtomLinter/linter-flake8#390]
Linter always reads 0, 0, 0  at the bottom of atom. There are no error messages that pop up. 

For a while I was fine with the following procedure. I would first open up terminal. Then, run the command ' source env/bin/activate'. And then, 'atom .' . This would open up atom and the linter would work fine. 

I got tired of having to switch between virtual enviroments  with so many commands , so I decided to try out virtualenvwrapper. After configuring things according to https://www.sitepoint.com/virtual-environments-python-made-easy/, I ran into issues with Linter-flake8. 

Flake 8 seems to be 'running' according to the busy signal symbol at the bottom of Atom. If I mouseover the busy symbol, it reports " History: Flake8 on .... (duration 0s)".

I'm completely lost. I'm not sure if this is a bug or if the problem is on my end. I would appreciate any help.

![screenshot 2017-04-12 21 02 31 2](https://cloud.githubusercontent.com/assets/14244727/24985619/6118509c-1fc3-11e7-9057-845c60e08e4a.png)

**Comment by muppetjones** [comment]
I think I'm having the same or similar issue. Atom says it's running Flake8, but nothing pops up. I know there are flake8 errors--I see them, and they're returned from the command line.

I'm not using virtualenvwrapper, though, and it doesn't seem to matter if I point to the global flake8, link to the global in the venv, or install flake8 locally. No errors or warnings are reported from Atom.

**Comment by muppetjones** [comment]
Found a solution for me: You need to start atom from the command line with the virtualenv already activated.
https://thoughtstreams.io/jtauber/python-3-print-flake8-problems/

**Comment by Arcanemagus** [comment]
@muppetjones You explicitly said you _weren't_ using a `virtualenv`, then said you solved the problem by doing the only way to get `virtualenv`s working 😛.

@cjm715 If I had to guess, something about your wrapper script isn't working properly. Most of these simply _don't_ work outside of a shell since they rely on shell macros to function. (Atom launches the process independently.)

You can try the workaround posted by @muppetjones above as that will let your virtualenv setup the environment, then you launch Atom from the pre-configured environment from the wrapper.

**Comment by Arcanemagus** [comment]
@cjm715 Can you try the latest release (v2.2.1)? I discovered that `flake8` crashes were being silently hidden from the user and fixed it so when `flake8` crashes something actually happens. It's quite possible you were running into this.

**Comment by cjm715** [comment]
the latest release worked for me! Thank you! I think this has been resolved.
