### ISSUE TITLE
flake8 keeps crashing again with BASH_FUNC_module

### ISSUE THREAD

**Issue by faassen** [AtomLinter/linter-flake8#422]
The error is "error importing function definition BASH_FUNC_module".

I used to have this problem but it's been gone for a while. Today I updated Atom from 1.15 to 1.16 and I possibly also updated linter-flake8, though I'm not sure about the latter. flake8 was at 3.2.1 and is now at 3.3.0 but the problem persists.

I had this problem a while back but upgrading flake8 fixed it. But now it has reappeared.

https://github.com/AtomLinter/linter-flake8/issues/165

**Comment by faassen** [comment]
Here's my resolution (in the hope it might help someone):

I removed the package ``environment-modules`` and things started working again. Apparently this messes up the bash environment in some way I don't understand.

I found the clue here:

https://github.com/AtomLinter/linter-puppet-lint/issues/68#issuecomment-238051151

**Comment by Arcanemagus** [comment]
It's possible some part of `environment-modules` requires an interactive shell, but is being loaded for non-interactive shells (such as the one used to run `flake8`).

Glad you got it figured out though!

**Comment by zeten30** [comment]
Hi, in my case Lmod package was the culprit (environment-modules package was not present on system).  /etc/profile.d/modules.sh is provided by multiple packages:

```
dnf provides /etc/profile.d/modules.sh
environment-modules-3.2.10-21.fc26.x86_64 : Provides dynamic modification of a user's environment
Repo        : updates-testing
Lmod-7.3.20-1.fc26.x86_64 : Environmental Modules System in Lua
Repo        : fedora
```

**Comment by Arcanemagus** [comment]
This is actually at it's root caused by https://github.com/steelbrain/consistent-env/issues/36 apparently.

**Comment by ddaanet** [comment]
Oh, interesting catch. I wonder why all the bug reports we have with this problem seem to come from fedora users though (but maybe that is only my selection bias).

**Comment by faassen** [comment]
I neglected to mention that "environment-modules" is a Fedora package. This definitely messes with the environment in some way I don't quite understand.

**Comment by ebaudrez** [comment]
Hi, it's definitely not restricted to Fedora. I'm on openSUSE and I'm experiencing the problem as well. As you probably know, the problem is caused by the `module` function (either from `environment-modules`, or `Modules` as the RPM is called on openSUSE, or Lmod). I'm reluctant to remove `Modules` because I actually use it!

Manually updating `consistent-env` to version 1.3.1, which should have solved the problem according to [this closed issue](https://github.com/steelbrain/consistent-env/pull/40), didn't work for me, but maybe I did something wrong as I'm very new to Node and `npm`. My current workaround is to launch a shell, issue `unset module` and launch atom from there. That works for me.
