### ISSUE TITLE
Flake8 rule 'E901' reported an invalid point

### ISSUE THREAD

**Issue by massilva** [AtomLinter/linter-flake8#468]
Flake8 reported an invalid point for the rule `E901`, with the messge `SyntaxError: invalid syntax`.

First line from file.py

Debug information:
Atom version: 1.18.0
Flake8 version: `2.5.4 (pep8: 1.5.7, pyflakes: 0.8.1, hacking.core: 0.0.1, ProxyChecker: 0.0.1, mccabe: 0.2.1) CPython 3.4.3 on Linux`

**Comment by massilva** [comment]
Syntax error was because another line

**Comment by Arcanemagus** [comment]
Please update your `flake8` version (`pip install -U flake8`). This particular error should be fixed in `flake8>=3.2.1`.

Note that this message is because your `flake8` version is actually reporting an impossible point for the location of the `E901` error, not because you had the error in the first place.
