### ISSUE TITLE
[Linter-Flake8] No error messages showing

### ISSUE THREAD

**Issue by IncoherentGuy** [AtomLinter/linter-flake8#480]
Hi, sorry for bothering, I have a problem. Im new to programming, and I just started with all of this. Since I want to learn Python as my first language, I installed Atom IDE. After installing Python too, couple packs from within Atom, which includes Flake8, I started programming, but no error messages were showing even if i wrote the code wrong. How to fix that? It will be a big help if someone could explain this to me, having in mind that I'm beginner and i don't know too much about this stuff.

 I installed the followings:
- pip install pep8
- pip install flake8
- pip install flake8-docstrings
- pip install hacking
But it still doesn't work.

Here is the screenshot of its settings
![untifhtled](https://user-images.githubusercontent.com/30579654/28757785-b318d110-758a-11e7-9644-632da957b75a.png)

Any help would be great!

**Comment by IncoherentGuy** [comment]
*UPDATE*
I somehow managed to make it work, up to a certain point at least. Problem is that error messages should look like this (material from the video tutorial that I have been watching)
![unteeeeeeeeeeeeeeeeeeeeeeitled](https://user-images.githubusercontent.com/30579654/28757955-457d5604-758e-11e7-9048-1e1bbcf0d410.png)

And my error messages are looking like this 

![qwd](https://user-images.githubusercontent.com/30579654/28757960-5d1f8b2e-758e-11e7-9b43-9d91a28b4f24.png)

If anyone can help me I would be very thankful!

**Comment by Arcanemagus** [comment]
I'm assuming you got things figured out since you've closed the issue?

**Comment by IncoherentGuy** [comment]
Yeah, but the new issue appeared. Now, it shows error messages even when I
write code as simple as hello world. I really don't know what to do. I
installed latest version of Python 3.6.2 and i did nothing with files I
installed. Then I installed Atom and just set Python as language. I'm
sending you screenshots. Also here are the packages I installed from Atom
sore. *Any help would be really appreciated!*

**Comment by IncoherentGuy** [comment]
![untitled](https://user-images.githubusercontent.com/30579654/28784178-ebbcaef0-7612-11e7-9abd-7bb52aa65ba7.png)
![untitled2](https://user-images.githubusercontent.com/30579654/28784179-ebc15004-7612-11e7-8713-9e9cfcc8f45b.png)
![untitled3](https://user-images.githubusercontent.com/30579654/28784177-ebbadc92-7612-11e7-901c-932740473bae.png)

**Comment by Arcanemagus** [comment]
Those messages are exactly what I would expect 😉.

PEP8 forbids whitespace before a `(` in a _function call_, it's _required_ before control logic such as `if`, or `for`. That's the `E211` error message.

Since you installed the `flake8-docstrings` module you are also getting messages about your docstrings, in this case you don't have a description for your "module".

**Comment by IncoherentGuy** [comment]
**Thank you so much!This means alot for me!**
So that means that everything is good with the installation of Atom and Python, and that I can start working with it? 
Any advice for a beginner?

**Comment by Arcanemagus** [comment]
It looks like everything is installed and working to me at least from your screenshots.

My personal advice for starting programming in an unfamiliar language is to get live linting feedback in your editor so you can see where you are potentially doing something wrong. Since you already have that covered you're about as far as I am as far as Python programming 😛.

**Comment by IncoherentGuy** [comment]
Hahah
Once again, thank you so much! 😄
