### ISSUE TITLE
OpenStack Style Guidelines "hacking" does not work with linter-flake8

### ISSUE THREAD

**Issue by elnygren** [AtomLinter/linter-flake8#485]
`pip install hacking` will install such an old version of flake8 that basic things like reading config from `tox.ini` breaks. Please consider removing this Optional suggestion from the README.md.

Steps to reproduce:
* `pip install hacking`
* `touch tox.ini`
* set tox.ini flake8 config to ignore H301
* put some imports in the wrong order
* flake8 is still going to warn about them even though it should not

**Comment by elnygren** [comment]
in addition, if you manually install a newer flake8, H*** codes won't work (Atom's lint command is not gonna say anything about H*** related issues)

**Comment by Arcanemagus** [comment]
You need to file this over on `hacking`, but don't get your hopes up since their `flake8` integration has been broken for a _long_ time.

Note that this package is just a wrapper around running `flake8`, you should find the same issues when trying to run things from the CLI.

If you _do_ install a version of `flake8` that is compatible with `hacking` it does show the errors, but as you note it's a positively ancient version where several things are broken.
