### ISSUE TITLE
is it possible to integrate windows-native atom with flake8 running in cygwin environment?

### ISSUE THREAD

**Issue by pipehat** [AtomLinter/linter-flake8#515]
atom error notification upon opening a python file:

linter-flake8:: Flake8 returned an error 
Failed to spawn command `c:\users\pipehat\.babun\cygwin\flake8`. Make sure `c:\users\pipehat\.babun\cygwin\flake8` is installed and on your PATH

I think the deal is, flake8 is a python shell script. Runs fine from a cygwin bash shell but not from windows command shell. When atom tries to spawn the flake8 process, it's in "windows world" so to speak and windows doesn't understand the shell script.

This isn't really a bug for linter-flake8 but perhaps there's a configuration option that would help make this work for me and others?

I could try setting the executable path to something like: bash -c "flake8" but then I don't think input/output would work as expected.

**Comment by Arcanemagus** [comment]
> help make this work for me

You'll need to create a batch wrapper script that calls the appropriate `python` on the script and passes all the arguments on to it. (Or alternatively just install Python on Windows and use `pip` to install it for you, which works perfectly.)

> and others

To be fair, I think this is the first issue requesting anything like this 😛.

> I could try setting the executable path to something like: bash -c "flake8"

You actually can't. The executable path is _literally_ that, arguments to `flake8` are a separate argument to the function that executes it.

Closing this since this really has nothing to do with `linter-flake8` but getting `flake8` installed correctly on your system. Feel free to keep posting here though and I'll try to help 😉.

**Comment by pipehat** [comment]
Totally fair. I agree installing windows-python and its own pip/flake8 env is likely the best path (pun?) forward.
