### ISSUE TITLE
Flake8 crash due to python path

### ISSUE THREAD

**Issue by simonmelouah** [AtomLinter/linter-flake8#524]
Hi, I keep getting the following error - obviously there's something wrong with the site packages flake8 is pointing to. Could you please clarify what needs to be done to resolve this? I'm using Mac OS High Sierra and have both Python 2.7 and 3.6 installed.

![image](https://user-images.githubusercontent.com/11134355/32653919-53d22b3a-c601-11e7-99f4-ce64229fc0b4.png)
![image](https://user-images.githubusercontent.com/11134355/32653996-a5ea2346-c601-11e7-8d40-6e0c358305c2.png)

**Comment by lucasdf** [comment]
Is there a reason why you have both "python2.7/site-packages" and "python3.6/site-packages" in your PYTHONPATH? PYTHONPATH is used to instruct the Python interpreter to look for packages in those directories. As it is now, the interpreter is looking for packages on both directories no matter what version of python is running. For instance, it may be running in python2.7 and it will try to load modules from python3, which will cause error.

What does it appear when you type `$PYTHONPATH` on the terminal?

I would recommend you to edit your PYTHONPATH and remove both entries, since Python already looks in the correct "site-packages" directory by default. Most likely the value is being set in the file `~/.bash_rc`, so you may want to start from there. If PYTHONPATH is not set there, you may want to look in other files in your home folder, like `~/.profile`.

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.
