### ISSUE TITLE
Failed to spawn command `flake8`.

### ISSUE THREAD

**Issue by cheney-github** [AtomLinter/linter-flake8#537]
linter-flake8:: Flake8 threw an error related to:
Failed to spawn command `flake8`. Make sure `flake8` is installed and on your PATH
Please check Atom's Console for more details

**Comment by Arcanemagus** [comment]
Have you installed `flake8`?

**Comment by stranjs** [comment]
I am having the same issue, this is the error from console, would appreciate any help.
<img width="717" alt="screen shot 2017-12-25 at 01 33 38" src="https://user-images.githubusercontent.com/3215160/34328804-b54f1226-e913-11e7-9e51-786e71cba2f7.png">

**Comment by Arcanemagus** [comment]
@stranjs Please read my earlier comment... you need `flake8` installed on your computer before this (`linter-flake8`) will work.

**Comment by DrummyBeat** [comment]
I am experiencing the same issue. I have, using a command prompt on windows 10 after adding python34 to my %PATH%, imported pip. 

After importing pip I have installed flake8 using the command in command prompt 
"python34 -m pip install flake8"

After installing flake8 I installed the linter-base through the atom program, not by using "$APM Install linter-flake8" as I have no clue where I would even input that.

I have gone through and tried checking my executable path for flake8 in atom, but I have no clue where or how I would find the path. If someone could give some explanation as to how to get it to work, in which program, command line, terminal, AND CODING LANGUAGE to install it, that would be great. So instead of saying "type in $apm install linter-flake8" explain WHERE YOU WOULD TYPE IT. Everything I've found on how to install just says the above, and is not helpful in the slightest.

**Comment by Arcanemagus** [comment]
@DrummyBeat You can check whether `flake8` is properly installed on your system using:
```batch
where.exe flake8
```

You should see something like this:
![image](https://user-images.githubusercontent.com/427137/35188172-ecf1a266-fde5-11e7-8654-cf5b08459e49.png)

If you instead get a `INFO: Could not find files for the given pattern(s).` message, then you either haven't properly installed `flake8`, or your `Scripts` folder isn't in your `PATH`.

----

If you don't have `linter-flake8` installed within Atom I would _highly_ recommend simply opening Atom's settings, going to Install, and searching for `linter-flake8`.

**Comment by DrummyBeat** [comment]
Problem solved. Didn't have my scripts folder in my PATH

**Comment by Arcanemagus** [comment]
Closing this due to a lack of response from @cheney-github.

**Comment by kenujen** [comment]
Where should flake8 be installed. I don't see an option to select location, so by default flake8 installed in: C:\Users\kenuj\AppData\Roaming\Python\Python37\Scripts, but my python3.7 is in C:\Program Files\Python\Python37\

Is this the reason it does not work? How do I install it correctly?

Thanks!

**Comment by Arcanemagus** [comment]
You may need to manually add the `C:\Users\kenuj\AppData\Roaming\Python\Python37\Scripts` to your `PATH` environment variable:
https://stackoverflow.com/a/44272417/631338

Note that you will need to restart any program (like Atom) that you want to see that change in after making it.

**Comment by kenujen** [comment]
Thanks!
I actually tried to add to PATH but was adding to the wrong path...

This works.

**Comment by DrummyBeat** [comment]
This solved my issue as well! Request to close thread
