### ISSUE TITLE
Tilde (~) fails to expand in Config File Names

### ISSUE THREAD

**Issue by mcandre** [AtomLinter/linter-flake8#58]
Please automatically expand tildes (`~`) in Config File Names to the current user's home directory. E.g., `~/.config/flake8` should expand to `/Users/andrew/.config/flake8` for user `andrew` on Mac OS X.

**Comment by binarious** [comment]
:+1: This is needed for other linter plugins, too. Atom-Beautify has already implemented this: https://github.com/Glavin001/atom-beautify/issues/235

**Comment by Arcanemagus** [comment]
There is no reliable cross-platform way to really do this. As setting this is a one time thing the slight inconvenience of having to type a few extra characters isn't really that big of an issue in my opinion.

@binarious the method used there isn't cross-platform.

I'm marking this as closed. If either of you want to submit a PR that implements this feel free but as it stands I see very little point in this.

**Comment by mcandre** [comment]
> There is no reliable cross-platform way to really do this.

`gsub ~ env.home`, or language implementation equivalent

**Comment by Arcanemagus** [comment]
@mcandre I'm assuming then that Ruby does all the hard work of figuring out `env.home` for you?

In any case since Atom itself is only supported on Windows 7 and above most of the broken platforms that make the task of determining the profile folder near impossible aren't an issue here, so something like https://github.com/npm/osenv could easily be used to accomplist this. Again, feel free to submit a PR.
