### ISSUE TITLE
Flake8 rule 'D101' reported an invalid point

### ISSUE THREAD

**Issue by xiashenzhen** [AtomLinter/linter-flake8#581]
Flake8 reported an invalid point for the rule `D101`, with the messge `Missing docstring in public class`.

Debug information:
Atom version: 1.25.0
Flake8 version: `3.5.0 (flake8-docstrings: 1.3.0, pydocstyle: 2.1.1, mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.6.0) CPython 3.6.5rc1 on Windows`

**Comment by Arcanemagus** [comment]
This is unlikely to be a bug in the parsing of `flake8`'s output here, but it _is_ possible. Are you able to share the file in the state that shows this error? If not, can you create a minimal reproduction case that you _can_ share?

If this turns out to be a bug in `flake8` it will need to be forwarded on to them before it is fixed.

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.
