### ISSUE TITLE
Flake8 rule 'E203' reported an invalid point

### ISSUE THREAD

**Issue by yechanggui** [AtomLinter/linter-flake8#586]
Flake8 reported an invalid point for the rule `E203`, with the messge `whitespace before ':'`.

Debug information:
Atom version: 1.21.2
Flake8 version: `3.5.0 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.6.0) CPython 2.7.10 on Darwin`

**Comment by Arcanemagus** [comment]
This is unlikely to be a bug in the parsing of `flake8`'s output here, but it _is_ possible. Are you able to share the file in the state that shows this error? If not, can you create a minimal reproduction case that you _can_ share?

If this turns out to be a bug in `flake8` it will need to be forwarded on to them before it is fixed.

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.
