### ISSUE TITLE
linter-flake8 not linting (not showing errors)

### ISSUE THREAD

**Issue by russellb23** [AtomLinter/linter-flake8#619]
Folks,

I have installed linter-flake8 in atom and it does installed linter as dependency. I have my flake8 installed in my python virtual environment. I have my path to flake8 supplied as follows
`/home/userlog/pythonvenv/bin/flake8`. But, nothing happens when I edit a python file. Could some expert shed some light on where to look and how to troubleshoot what I am doing wrong? Or is it a issue, as I see `linter` in github with status build-failing.

Thanks in advance,

**Comment by rafacarrascosa** [comment]
Hi @russellb23 ,

I had the same issue, in my case I 'solved' it by starting atom in a folder that has no git o virtualenv, like: `atom path/to/empty/dir`.

My guess is that per project/git/virtualenv settings confuse this package.

Hope it helps in your case too.
Cheers

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.

If you are still having issues @russellb23 make sure that the file you have open is recognized as Python and is getting matched to this provider by running `Linter: Debug` from the Command Palette. You _should_ see "flake8" in the list of Matching Providers, as well as "Open file is Ignored: No".
