### ISSUE TITLE
Linter-Flake8 [Error Running Flake8]

### ISSUE THREAD

**Issue by qutianch** [AtomLinter/linter-flake8#644]
See Console for more info. (Open View -> Developer -> Toggle Developer Tools)
Hi there,
I couldn't get linter-flake8 running on my Atom with python 3.7.
I installed the flake8 with pip but no working. 

Please help

Thanks

**Comment by Arcanemagus** [comment]
You're hitting https://github.com/PyCQA/pycodestyle/issues/728 @Radobilly.

And yes, it's highly likely that @qutianch is hitting the same thing, but without more information it's impossible to say for sure. Since you haven't answered yet @qutianch I'm going to close this, but if you are still having problems feel free to update this issue!

**Comment by RebelCoderRU** [comment]
Hello. This problem is still present. I have installed Atom and configured it the same way on two PC's and on one of them it just does not work.

Error message:
![image](https://user-images.githubusercontent.com/20476773/50485703-4a01a900-09ee-11e9-8d84-72389901e867.png)

Logs:
![image](https://user-images.githubusercontent.com/20476773/50485732-6a316800-09ee-11e9-9615-d4b4b9618e52.png)


```
linter-registry.js? [sm]:137 [Linter] Error running Flake8 Error: /home/jurisl/.local/lib/python3.7/site-packages/pep8.py:110: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')

    at ChildProcess.<anonymous> (/home/jurisl/.atom/packages/linter-flake8/node_modules/sb-exec/lib/index.js:56)
    at emitTwo (events.js:126)
    at ChildProcess.emit (events.js:214)
    at maybeClose (internal/child_process.js:925)
    at Socket.stream.socket.on (internal/child_process.js:346)
    at emitOne (events.js:116)
    at Socket.emit (events.js:211)
    at Pipe._handle.close [as _onclose] (net.js:554)
```

```
whereis flake8
flake8: /home/jurisl/.local/bin/flake8

flake8 --version
/home/jurisl/.local/lib/python3.7/site-packages/pep8.py:110: FutureWarning: Possible nested set at position 1
EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
3.7.0dev0 (flake8-docstrings: 1.3.0, pydocstyle: 3.0.0, mccabe: 0.6.1, pycodestyle: 2.4.0, pyflakes: 2.0.0) CPython 3.7.2rc1 on Linux

python --version
Python 3.7.2rc1

echo $PATH
/home/jurisl/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:
/usr/games:/home/jurisl/.local/bin

```
