### ISSUE TITLE
Flake8 rule 'D401' reported an invalid point

### ISSUE THREAD

**Issue by karrukola** [AtomLinter/linter-flake8#645]
Flake8 reported an invalid point for the rule `D401`, with the messge `First line should be in imperative mood`.

`#!/usr/bin/env python
"""This module provides methods for dns parsing"""
import dns.resolver
from dns.rdatatype import A, AAAA

def _query_and_parse_dns(address, r_data_type):
    """Queries and returns the addresses resolved for given datatype"""
    answers = dns.resolver.query(address, rdtype=r_data_type)
    for r_data in answers:
        print r_data
    return [str(r_data) for r_data in answers]

_query_and_parse_dns("google.com", A)`

Debug information:
Atom version: 1.31.2
Flake8 version: `3.5.0 (flake8-docstrings: 1.3.0, pydocstyle: 2.1.1, mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.6.0) CPython 2.7.15 on Windows`

**Comment by Arcanemagus** [comment]
This is unlikely to be a bug in the parsing of `flake8`'s output here, but it _is_ possible. Are you able to share the file in the state that shows this error? If not, can you create a minimal reproduction case that you _can_ share?

If this turns out to be a bug in `flake8` it will need to be forwarded on to them before it is fixed.

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.
