### ISSUE TITLE
Flake8 rule 'D102' reported an invalid point

### ISSUE THREAD

**Issue by NikhilDikshit** [AtomLinter/linter-flake8#652]
Flake8 reported an invalid point for the rule `D102`, with the messge `Missing docstring in public method`.

Debug information:
Atom version: 1.31.2
Flake8 version: `3.5.0 (flake8-docstrings: 1.3.0, pydocstyle: 3.0.0, mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.6.0) CPython 2.7.15rc1 on Linux`

**Comment by Arcanemagus** [comment]
This is unlikely to be a bug in the parsing of `flake8`'s output here, but it _is_ possible. Are you able to share the file in the state that shows this error? If not, can you create a minimal reproduction case that you _can_ share?

If this turns out to be a bug in `flake8` it will need to be forwarded on to them before it is fixed.

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.
