### ISSUE TITLE
Linter v1 Support Dropped

### ISSUE THREAD

**Issue by IbrH** [AtomLinter/linter-flake8#665]
I'm trying to lint a python file, but it's getting ignored.
Linter: Debug outputs this:
```
Platform: linux
Atom Version: 1.33.1
Linter Version: 2.3.0
Opened file is ignored: No
Matching Linter Providers: 
Disabled Linter Providers: 
Standard Linter Providers: 
Indie Linter Providers: 
UI Providers: 
  - Linter
Ignore Glob: **/*.min.{js,css}
VCS Ignored Paths are excluded: true
Current File Scopes: 
  - *
  - source.python
```
What do I need to do to make it work?

**Comment by richardbann** [comment]
This is most probably because you updated linter (https://atom.io/packages/linter) to a version which does not work with the linter v1 protocol. Until this package is updated, we have to stay with the older linter version (2.1.2).

I have a working local version but it is mostly a hack. Let us see what the maintainers of this package think. I can create a pull request if nobody else is working on it.

**Comment by Arcanemagus** [comment]
Wow, dropping v1 support _should_ have been a major release 🤦‍♂️.

@richardbann feel free to send up a PR, we can always fix it in the review process 😉. There's a guid on migrating [here](https://github.com/steelbrain/linter/blob/9a51575d1af9da2932d9db22d400b8924d0a49a4/docs/guides/upgrading-to-standard-linter-v2.md) if you haven't seen it yet. Let me know if you need any help!

**Comment by timduly4** [comment]
I had a similar issue, and I resolved this by uninstalling the `linter` package and reinstalling via:
```
$ apm install linter@2.2.0
```

**Comment by Arcanemagus** [comment]
v2.4.0 should fix this thanks to @richardbann's PR 🎉.
