### ISSUE TITLE
Windows 10 - Doesn't "flake" the code.

### ISSUE THREAD

**Issue by jkw** [AtomLinter/linter-flake8#67]
* atom v1.0.7
* linter v1.3.4
* linter-flake8 v1.6.0
* python v3.5b2
  * flake8-2.4.1
  * pyflakes-0.8.1
  * mccabe-0.3.1
  * pep8-1.5.7

Tried open a clean new Django App, which should shout on unused imported module. But it doesn't. When I run `flake8.exe views.py` it spits out proper error message:
>.\views.py:1:1: F401 'render' imported but unused

Shout if you need more information.

**Comment by Arcanemagus** [comment]
It's working perfectly fine on Win10 with a similar setup except for the Python version. Since `linter-flake8` simply parses the output of running `flake8` though that shouldn't be an issue.

Has it ever worked for you before?

Can you go into the Developer Tools and put a breakpoint at line 76 of main.coffee and make sure there is actually output from running `flake8`?

**Comment by badray** [comment]
@jkw  I dont have windows 10, but on windows 8.1 it works properly. Please work with @Arcanemagus to resolve issue.

**Comment by jkw** [comment]
Line 76 of main.coffee:
`var col, line, match, regex, toReturn;`

No errors whatsoever in dev tools.

Rolled back to Python 3.4.3, same here nothing happens. I don't know what I'm doing wrong. :-/

**Comment by Arcanemagus** [comment]
Looks like a release was pushed out _just_ as you posted that last comment that enables lintOnFly for this plugin.

**Comment by Arcanemagus** [comment]
@jkw can you close this issue as it's working for you?
