### ISSUE TITLE
I can't run linter-flake8 on my mac! 

### ISSUE THREAD

**Issue by flyer13** [AtomLinter/linter-flake8#692]
Hey guys,

When I try to install "linter-flake8" using mac terminal "pip install flake8"
 I got this error message " Cannot uninstall 'entrypoints'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall."

Any ideas on how to fix this issue and let this package work perfectly?

<img width="573" alt="Screen Shot 2019-04-29 at 16 51 14" src="https://user-images.githubusercontent.com/22845509/56900811-634f5a80-6a9f-11e9-8ccd-bc04b24e289e.png">

**Comment by Arcanemagus** [comment]
A quick search shows [the workaround](https://stackoverflow.com/questions/49932759/pip-10-and-apt-how-to-avoid-cannot-uninstall-x-errors-for-distutils-packages), however it sounds like you are still using the system installation of `python` which is positively _ancient_. You are likely better off figuring out how to install a current version of Python on your system and using that instead of the one included with your OS.

Marking this as closed since this is an issue with installing `flake8`, nothing to actually do with `linter-flake8`.
